export function createAppState({
  route = "/",
  products = [],
  wishlist = [],
  notifications = {},
  coupons = [],
  posts = [],
  adminProfile = {},
  adminBanners = [],
  authRedirect = "/mypage",
} = {}) {
  return {
    route,
    products,
    cart: [],
    wishlist,
    orders: [],
    viewer: null,
    authSession: null,
    authUser: null,
    authReady: false,
    authBusy: false,
    authRedirect,
    accountLoading: false,
    authRoles: [],
    authRolesLoaded: false,
    addresses: [],
    paymentMethods: [],
    notifications,
    coupons,
    posts,
    activeBanner: 0,
    pendingScrollTarget: null,
    postSearch: "",
    expandedInquiryId: null,
    selected: {},
    myTab: "orders",
    selectedReviewOrderId: "",
    signupLoginCheck: { loginId: "", status: "idle", message: "" },
    adminTab: "dashboard",
    adminProfile,
    adminBanners,
    adminCustomers: [],
    adminMembers: [],
    adminMembersLoading: false,
    adminMembersLoaded: false,
    adminMembersError: "",
    adminProducts: [],
    remoteProducts: [],
    adminModal: null,
    adminModalContext: null,
    adminSearch: "",
    adminLoginError: "",
    menuOpen: false,
    cartPromptOpen: false,
    consultOpen: false,
    consultMessages: [],
    heroIntroHasPlayed: false,
    checkoutBusy: false,
    checkoutIdempotencyKey: "",
    paymentRequestState: "idle",
    adminGateBusy: false,
  };
}
